language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: DZI0OrhKW4ltHXSMoIX2ePN7towMeMMvC/tciZj6qOhlH13CeY19ZMFiBmD3/jMN9xVPItgoYIU6af4/oAiBBIDiSNe+BJWfzIAjQF6Zac2T/uiQ8VIeztSgbBcxD/epJYDPMiCCW+iu74QLWiNuyBhkL5SUjrB6ssHxS/qo/v99RxvDhQn77siTZbV4KdDh6JU9WHt7OCgBioLfjGUimT4zrW0GpaD2Hau42BBdKOPbExhI26kRZYArpxhR9coALgEEgIAKeTq/CZEFkOA//27QBTl6rR8S4aus2Cb+gt2aUUKkCiE/Lj5VlKGwOd9E0RpRCqR3ukUw/kK4Ly9s+1Iq/XLHEE90qObm/XkHdLE6O6IQIqgelR+PNJuj6xGJLoGCgBVH9sHGAwGUXs3lA/M2blsrUaM7ApGNyvo/Dn5wIyDWJL20EHh9IN9lA0wqu30Lnh73Lu4OX/SQUlVAoa4jS5WOsEaaGPWKGWRJzw4nLIfz4CDjv/J8h5wsihqKWfM2C8ndoL+CZ8QAw6b9JnLI114bZYkReJGg/aR0Yb0ouDaYm19RL2Uciow8UW3bIsMCYJ3AhzxQIltJsh7xdU5+DVYjLIZBaX2gnQGS2iptB0Tz7YVawtMDJ0ZxIGQI4hfsGGno4Fj43wnPnqwUdahNy+wXT3vQsztSCrc7Kw4=
  app: react-trello-thinkful
  on:
    repo: claytonweller/react-trello-testing
