language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: ShRHV9wgLjd8ws1JpNvLujGkNqEZHJ2Wf1XQ1pIGxKKo3ifbV009u6YOaMlPBmy93EJkBjNYHpSInWXzShAbULo/eHOjYP/xMDr2xFgIQVSEC+frJyjhQRKI5Liw2SwEQRvAJ2HOwTkVHKKP0AzkSPVo9zhxr23KLDHtXxfqhj0o8c52JyJ15eFz7K33ADG8gdICU9dcyIhV8Z1cHbU3NwOVgj/egQD5Hw39Vgw0ehLqBLKMs1t9JbD3AM2EcAAD9eh4M07FJyB9a7LO/8bLotJj4ghowiHTYj+TliP2vwqHlH/dF/DSPmsZFpkbqOeE9BBJ9wZCjLZWOGYjOADp4lYf+V+aYE3Lj6IvCN2nEh0NJQ/CAKTCM68jCkzV2BKrnn5W2ziCIQ5EvSaSlCoDV8xtgjL0pZW/q6BqAZiB1mlIz6d6n1Pblg/3s6MW/MzXVdi2UEddm8/xnc4iPla271BGH/XyJWZNAjZy8Z1lD2y4atSY06q+deVHPRLQjq3B+g6Rq6TCnSghK3p4aKM/903xv+o/a6GqYIuaZ/K/Tlo9Mt0P/dcTiJKDXtED7x153TwZ5hVoEuoV+jJ5+OQPjRutMAswQZpds5DXiH4ia2ZOJb0DZ1ww4F32JiFaWt4Kr6bvZEpt3P1o5p8p+0ezxAc5r765r38xhZl/VuZJYh8=
  app: react-trello-testing
  on:
    repo: claytonweller/react-trello-testing
